-- Corte de caja por usuario, movimientos manuales y conciliación de abonos.
-- Ejecutar una sola vez desde Supabase SQL Editor.
begin;

alter table public.configuracion_sistema
    add column if not exists caja_requerida_para_operar boolean not null default false,
    add column if not exists caja_recordatorio_cierre boolean not null default true,
    add column if not exists caja_horario_apertura time without time zone not null default '08:00',
    add column if not exists caja_horario_cierre time without time zone not null default '18:00',
    add column if not exists caja_recordatorio_minutos smallint not null default 30;

alter table public.configuracion_sistema
    drop constraint if exists configuracion_sistema_recordatorio_caja_valido;
alter table public.configuracion_sistema
    add constraint configuracion_sistema_recordatorio_caja_valido
    check (caja_recordatorio_minutos between 0 and 240);

create table if not exists public.cortes_caja (
    id bigint generated by default as identity primary key,
    usuario_id integer not null references public.usuarios(id),
    empleado_id integer references public.empleados(id),
    estado text not null default 'abierta' check (estado in ('abierta', 'cerrada')),
    monto_inicial numeric(12, 2) not null default 0 check (monto_inicial >= 0),
    monto_esperado_cierre numeric(12, 2),
    monto_contado_cierre numeric(12, 2),
    diferencia_cierre numeric(12, 2),
    notas_apertura text,
    notas_cierre text,
    fecha_apertura timestamp with time zone not null default now(),
    fecha_cierre timestamp with time zone,
    creado_en timestamp with time zone not null default now(),
    actualizado_en timestamp with time zone not null default now(),
    constraint cortes_caja_cierre_coherente check (
        (estado = 'abierta' and fecha_cierre is null)
        or
        (estado = 'cerrada' and fecha_cierre is not null)
    )
);

create unique index if not exists idx_cortes_caja_usuario_abierta
    on public.cortes_caja(usuario_id)
    where estado = 'abierta';
create index if not exists idx_cortes_caja_fecha
    on public.cortes_caja(fecha_apertura desc);

create table if not exists public.cuentas_financieras (
    id bigint generated by default as identity primary key,
    nombre text not null,
    tipo text not null check (tipo in ('efectivo', 'banco', 'terminal', 'billetera', 'otro')),
    activo boolean not null default true,
    orden smallint not null default 0,
    creado_en timestamp with time zone not null default now(),
    actualizado_en timestamp with time zone not null default now()
);

create unique index if not exists idx_cuentas_financieras_nombre_unico
    on public.cuentas_financieras(lower(trim(nombre)));

insert into public.cuentas_financieras(nombre, tipo, orden)
values
    ('Efectivo', 'efectivo', 0),
    ('Tarjeta', 'terminal', 10),
    ('Transferencia', 'banco', 20),
    ('Otros medios', 'otro', 30)
on conflict do nothing;

alter table public.cortes_caja
    add column if not exists resumen_cuentas jsonb not null default '{}'::jsonb,
    add column if not exists conteo_cierre_cuentas jsonb not null default '{}'::jsonb,
    add column if not exists diferencias_cuentas jsonb not null default '{}'::jsonb;

create table if not exists public.movimientos_caja (
    id bigint generated by default as identity primary key,
    corte_id bigint not null references public.cortes_caja(id) on delete restrict,
    usuario_id integer not null references public.usuarios(id),
    empleado_id integer references public.empleados(id),
    tipo text not null check (tipo in ('deposito', 'retiro', 'gasto')),
    monto numeric(12, 2) not null check (monto > 0),
    concepto text not null check (length(trim(concepto)) >= 3),
    referencia text,
    creado_en timestamp with time zone not null default now()
);

alter table public.movimientos_caja
    add column if not exists cuenta_financiera_id bigint references public.cuentas_financieras(id);

create index if not exists idx_movimientos_caja_corte
    on public.movimientos_caja(corte_id, creado_en desc);

alter table public.orden_abonos
    add column if not exists corte_caja_id bigint references public.cortes_caja(id);
alter table public.orden_abonos
    add column if not exists metodo_pago text not null default 'efectivo',
    add column if not exists metodo_pago_otro text,
    add column if not exists cantidad_recibida numeric(12, 2),
    add column if not exists cambio_entregado numeric(12, 2);
alter table public.orden_abonos
    add column if not exists cuenta_financiera_id bigint references public.cuentas_financieras(id);
create index if not exists idx_orden_abonos_corte_caja
    on public.orden_abonos(corte_caja_id, fecha_abono);

update public.movimientos_caja m
   set cuenta_financiera_id = (
       select id from public.cuentas_financieras
        where tipo = 'efectivo' order by orden, id limit 1
   )
 where m.cuenta_financiera_id is null;

update public.orden_abonos a
   set cuenta_financiera_id = (
      select id
        from public.cuentas_financieras
       where tipo = case lower(coalesce(a.metodo_pago, 'efectivo'))
           when 'efectivo' then 'efectivo'
           when 'tarjeta' then 'terminal'
           when 'transferencia' then 'banco'
           else 'otro'
       end
       order by orden, id limit 1
  )
 where a.cuenta_financiera_id is null;

create or replace function public.vincular_abono_corte_caja_app()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
    if new.corte_caja_id is null and new.registrado_por_empleado_id is not null then
        select c.id
          into new.corte_caja_id
          from public.cortes_caja c
         where c.estado = 'abierta'
           and c.empleado_id = new.registrado_por_empleado_id
         order by c.fecha_apertura desc
         limit 1;
    end if;
    if new.cuenta_financiera_id is null then
        select cf.id
          into new.cuenta_financiera_id
          from public.cuentas_financieras cf
         where cf.activo
           and (
                (lower(coalesce(new.metodo_pago, 'efectivo')) = 'efectivo' and cf.tipo = 'efectivo')
                or (lower(coalesce(new.metodo_pago, '')) = 'tarjeta' and cf.tipo = 'terminal')
                or (lower(coalesce(new.metodo_pago, '')) = 'transferencia' and cf.tipo = 'banco')
                or (lower(coalesce(new.metodo_pago, '')) = 'otro' and cf.tipo = 'otro')
           )
         order by cf.orden, cf.id
         limit 1;
    end if;
    return new;
end;
$$;

drop trigger if exists trg_vincular_abono_corte_caja on public.orden_abonos;
create trigger trg_vincular_abono_corte_caja
before insert on public.orden_abonos
for each row execute function public.vincular_abono_corte_caja_app();

create or replace function public.cerrar_corte_caja_app(
    p_corte_id bigint,
    p_usuario_id integer,
    p_monto_contado numeric,
    p_notas text default null
)
returns public.cortes_caja
language plpgsql
security definer
set search_path = public
as $$
declare
    v_corte public.cortes_caja;
    v_efectivo numeric(12, 2) := 0;
    v_entradas numeric(12, 2) := 0;
    v_salidas numeric(12, 2) := 0;
    v_esperado numeric(12, 2) := 0;
begin
    if p_monto_contado < 0 then
        raise exception 'El efectivo contado no puede ser negativo';
    end if;

    select * into v_corte
      from public.cortes_caja
     where id = p_corte_id
       and usuario_id = p_usuario_id
       and estado = 'abierta'
     for update;

    if not found then
        raise exception 'No se encontró una caja abierta para este usuario';
    end if;

    select coalesce(sum(cantidad), 0)
      into v_efectivo
      from public.orden_abonos
     where corte_caja_id = p_corte_id
       and lower(coalesce(metodo_pago, 'efectivo')) = 'efectivo';

    select
        coalesce(sum(m.monto) filter (where m.tipo = 'deposito'), 0),
        coalesce(sum(m.monto) filter (where m.tipo in ('retiro', 'gasto')), 0)
      into v_entradas, v_salidas
      from public.movimientos_caja m
      left join public.cuentas_financieras cf on cf.id = m.cuenta_financiera_id
     where m.corte_id = p_corte_id
       and (cf.tipo = 'efectivo' or m.cuenta_financiera_id is null);

    v_esperado := v_corte.monto_inicial + v_efectivo + v_entradas - v_salidas;

    update public.cortes_caja
       set estado = 'cerrada',
           monto_esperado_cierre = v_esperado,
           monto_contado_cierre = p_monto_contado,
           diferencia_cierre = p_monto_contado - v_esperado,
           notas_cierre = nullif(trim(coalesce(p_notas, '')), ''),
           fecha_cierre = now(),
           actualizado_en = now()
     where id = p_corte_id
     returning * into v_corte;

    return v_corte;
end;
$$;

grant select, insert, update on public.cortes_caja to anon, authenticated, service_role;
grant usage, select on sequence public.cortes_caja_id_seq to anon, authenticated, service_role;
grant select, insert on public.movimientos_caja to anon, authenticated, service_role;
grant usage, select on sequence public.movimientos_caja_id_seq to anon, authenticated, service_role;
grant select, insert, update on public.cuentas_financieras to anon, authenticated, service_role;
grant usage, select on sequence public.cuentas_financieras_id_seq to anon, authenticated, service_role;
grant select, update on public.orden_abonos to anon, authenticated, service_role;
grant execute on function public.cerrar_corte_caja_app(bigint, integer, numeric, text)
    to anon, authenticated, service_role;

insert into public.permisos (codigo, modulo, nombre)
values ('front.cash.manage', 'mostrador', 'Abrir, operar y cerrar caja')
on conflict (codigo) do update
set modulo = excluded.modulo, nombre = excluded.nombre;

notify pgrst, 'reload schema';
commit;
