-- Existencia actual e historial de entradas de inventario.
-- Ejecutar una sola vez desde Supabase SQL Editor.
begin;

alter table public.reactivos
    add column if not exists existencia_actual integer;

update public.reactivos
set existencia_actual = greatest(coalesce(cantidad_inicial, 0), 0)
where existencia_actual is null;

alter table public.reactivos
    alter column existencia_actual set default 0,
    alter column existencia_actual set not null;

create or replace function public.inicializar_existencia_reactivo()
returns trigger
language plpgsql
set search_path = public
as $$
begin
    new.existencia_actual := greatest(coalesce(new.cantidad_inicial, 0), 0);
    return new;
end;
$$;

drop trigger if exists trg_inicializar_existencia_reactivo on public.reactivos;
create trigger trg_inicializar_existencia_reactivo
before insert on public.reactivos
for each row execute function public.inicializar_existencia_reactivo();

create table if not exists public.movimientos_inventario (
    id bigint generated by default as identity primary key,
    reactivo_id bigint not null references public.reactivos(id),
    tipo text not null check (tipo in ('entrada', 'salida', 'ajuste')),
    cantidad integer not null check (cantidad > 0),
    existencia_anterior integer not null check (existencia_anterior >= 0),
    existencia_nueva integer not null check (existencia_nueva >= 0),
    costo_unitario numeric(12, 2),
    numero_lote text,
    fecha_vencimiento date,
    observaciones text,
    registrado_por_empleado_id integer references public.empleados(id),
    creado_en timestamp with time zone not null default now()
);

create index if not exists idx_movimientos_inventario_reactivo
    on public.movimientos_inventario(reactivo_id, creado_en desc);

create index if not exists idx_movimientos_inventario_fecha
    on public.movimientos_inventario(creado_en desc);

create or replace function public.registrar_entrada_inventario(
    p_reactivo_id bigint,
    p_cantidad integer,
    p_costo_unitario numeric default null,
    p_numero_lote text default null,
    p_fecha_vencimiento date default null,
    p_observaciones text default null,
    p_empleado_id integer default null
)
returns jsonb
language plpgsql
security invoker
set search_path = public
as $$
declare
    v_reactivo public.reactivos%rowtype;
    v_nueva_existencia integer;
    v_movimiento_id bigint;
begin
    if p_cantidad is null or p_cantidad <= 0 then
        raise exception 'La cantidad debe ser mayor que cero';
    end if;

    select *
      into v_reactivo
      from public.reactivos
     where id = p_reactivo_id
       and activo is true
     for update;

    if not found then
        raise exception 'El reactivo no existe o está inactivo';
    end if;

    v_nueva_existencia := v_reactivo.existencia_actual + p_cantidad;

    update public.reactivos
       set existencia_actual = v_nueva_existencia,
           costo_unidad = coalesce(p_costo_unitario, costo_unidad)
     where id = p_reactivo_id;

    insert into public.movimientos_inventario (
        reactivo_id, tipo, cantidad, existencia_anterior, existencia_nueva,
        costo_unitario, numero_lote, fecha_vencimiento, observaciones,
        registrado_por_empleado_id
    )
    values (
        p_reactivo_id, 'entrada', p_cantidad, v_reactivo.existencia_actual,
        v_nueva_existencia, p_costo_unitario, nullif(trim(p_numero_lote), ''),
        p_fecha_vencimiento, nullif(trim(p_observaciones), ''), p_empleado_id
    )
    returning id into v_movimiento_id;

    return jsonb_build_object(
        'movimiento_id', v_movimiento_id,
        'existencia_anterior', v_reactivo.existencia_actual,
        'existencia_nueva', v_nueva_existencia
    );
end;
$$;

comment on column public.reactivos.existencia_actual is
    'Existencia disponible; cantidad_inicial conserva el valor con el que se creó el reactivo.';

comment on table public.movimientos_inventario is
    'Historial auditable de entradas, salidas y ajustes de reactivos.';

commit;
