-- Flujo de pruebas procesadas por laboratorios/proveedores de referencia.
-- Ejecutar una sola vez desde Supabase SQL Editor.
begin;

alter table public.pruebas_clinicas
    add column if not exists procesamiento text not null default 'interno',
    add column if not exists proveedor_servicio_id bigint references public.proveedores(id),
    add column if not exists tipo_muestra_externa text,
    add column if not exists recipiente_muestra text,
    add column if not exists conservacion_muestra text,
    add column if not exists volumen_minimo text,
    add column if not exists tiempo_entrega_dias integer,
    add column if not exists instrucciones_envio text,
    add column if not exists costo_proveedor numeric(12,2);

do $$
begin
    if not exists (
        select 1 from pg_constraint
        where conname = 'pruebas_clinicas_procesamiento_check'
    ) then
        alter table public.pruebas_clinicas
            add constraint pruebas_clinicas_procesamiento_check
            check (procesamiento in ('interno', 'externo'));
    end if;
    if not exists (
        select 1 from pg_constraint
        where conname = 'pruebas_clinicas_externa_proveedor_check'
    ) then
        alter table public.pruebas_clinicas
            add constraint pruebas_clinicas_externa_proveedor_check
            check (procesamiento = 'interno' or proveedor_servicio_id is not null);
    end if;
    if not exists (
        select 1 from pg_constraint
        where conname = 'pruebas_clinicas_entrega_check'
    ) then
        alter table public.pruebas_clinicas
            add constraint pruebas_clinicas_entrega_check
            check (tiempo_entrega_dias is null or tiempo_entrega_dias >= 0);
    end if;
end $$;

alter table public.orden_pruebas_detalle
    add column if not exists procesamiento text not null default 'interno',
    add column if not exists proveedor_servicio_id bigint references public.proveedores(id);

create table if not exists public.estudios_externos (
    id bigint generated by default as identity primary key,
    orden_detalle_id bigint not null unique references public.orden_pruebas_detalle(id) on delete cascade,
    orden_id bigint not null references public.ordenes(id) on delete cascade,
    prueba_id bigint references public.pruebas_clinicas(id),
    proveedor_id bigint not null references public.proveedores(id),
    estado text not null default 'muestra_pendiente' check (estado in (
        'muestra_pendiente', 'listo_envio', 'enviado', 'recibido_proveedor',
        'resultado_recibido', 'validado', 'rechazado',
        'requiere_nueva_muestra', 'cancelado'
    )),
    tipo_muestra text,
    recipiente text,
    conservacion text,
    volumen_minimo text,
    instrucciones text,
    tiempo_entrega_dias integer,
    costo_proveedor numeric(12,2),
    referencia_proveedor text,
    fecha_prometida date,
    listo_envio_en timestamp with time zone,
    enviado_en timestamp with time zone,
    recibido_proveedor_en timestamp with time zone,
    resultado_recibido_en timestamp with time zone,
    validado_en timestamp with time zone,
    documento_resultado_path text,
    observaciones text,
    creado_por_usuario_id integer references public.usuarios(id),
    actualizado_por_usuario_id integer references public.usuarios(id),
    creado_en timestamp with time zone not null default now(),
    actualizado_en timestamp with time zone not null default now()
);

create table if not exists public.envios_proveedor (
    id bigint generated by default as identity primary key,
    proveedor_id bigint not null references public.proveedores(id),
    estado text not null default 'preparacion' check (estado in (
        'preparacion', 'enviado', 'recibido_parcial', 'cerrado', 'cancelado'
    )),
    mensajeria text,
    numero_guia text,
    fecha_prometida date,
    enviado_en timestamp with time zone,
    observaciones text,
    creado_por_usuario_id integer references public.usuarios(id),
    creado_en timestamp with time zone not null default now(),
    actualizado_en timestamp with time zone not null default now()
);

create table if not exists public.envios_proveedor_detalle (
    id bigint generated by default as identity primary key,
    envio_id bigint not null references public.envios_proveedor(id) on delete cascade,
    estudio_externo_id bigint not null unique references public.estudios_externos(id),
    creado_en timestamp with time zone not null default now()
);

create index if not exists idx_pruebas_procesamiento on public.pruebas_clinicas(procesamiento);
create index if not exists idx_pruebas_proveedor_servicio on public.pruebas_clinicas(proveedor_servicio_id);
create index if not exists idx_externos_orden on public.estudios_externos(orden_id);
create index if not exists idx_externos_proveedor_estado on public.estudios_externos(proveedor_id, estado);
create index if not exists idx_externos_fecha_prometida on public.estudios_externos(fecha_prometida);
create index if not exists idx_envios_proveedor on public.envios_proveedor(proveedor_id, creado_en desc);

create or replace function public.validar_proveedor_prueba_externa_app()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
    v_es_servicio boolean;
begin
    if new.procesamiento <> 'externo' then
        return new;
    end if;
    select (tipo = 'servicio' and activo is true)
      into v_es_servicio
      from public.proveedores
     where id = new.proveedor_servicio_id;
    if coalesce(v_es_servicio, false) is not true then
        raise exception 'La prueba externa requiere un proveedor activo marcado como servicio';
    end if;
    return new;
end;
$$;

drop trigger if exists trg_validar_proveedor_prueba_externa on public.pruebas_clinicas;
create trigger trg_validar_proveedor_prueba_externa
before insert or update of procesamiento, proveedor_servicio_id
on public.pruebas_clinicas
for each row execute function public.validar_proveedor_prueba_externa_app();

create or replace function public.sincronizar_detalle_prueba_externa_app()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
    v_prueba public.pruebas_clinicas%rowtype;
begin
    if new.prueba_id is null then
        return new;
    end if;
    select * into v_prueba from public.pruebas_clinicas where id = new.prueba_id;
    if found then
        new.procesamiento := coalesce(v_prueba.procesamiento, 'interno');
        new.proveedor_servicio_id := v_prueba.proveedor_servicio_id;
    end if;
    return new;
end;
$$;

drop trigger if exists trg_sincronizar_detalle_prueba_externa on public.orden_pruebas_detalle;
create trigger trg_sincronizar_detalle_prueba_externa
before insert or update of prueba_id on public.orden_pruebas_detalle
for each row execute function public.sincronizar_detalle_prueba_externa_app();

create or replace function public.crear_seguimiento_estudio_externo_app()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
    v_prueba public.pruebas_clinicas%rowtype;
begin
    if new.procesamiento <> 'externo' or new.prueba_id is null then
        delete from public.estudios_externos where orden_detalle_id = new.id;
        return new;
    end if;

    select * into v_prueba from public.pruebas_clinicas where id = new.prueba_id;
    insert into public.estudios_externos (
        orden_detalle_id, orden_id, prueba_id, proveedor_id, tipo_muestra,
        recipiente, conservacion, volumen_minimo, instrucciones,
        tiempo_entrega_dias, costo_proveedor
    ) values (
        new.id, new.orden_id, new.prueba_id, new.proveedor_servicio_id,
        v_prueba.tipo_muestra_externa, v_prueba.recipiente_muestra,
        v_prueba.conservacion_muestra, v_prueba.volumen_minimo,
        v_prueba.instrucciones_envio, v_prueba.tiempo_entrega_dias,
        v_prueba.costo_proveedor
    )
    on conflict (orden_detalle_id) do update set
        proveedor_id = excluded.proveedor_id,
        tipo_muestra = excluded.tipo_muestra,
        recipiente = excluded.recipiente,
        conservacion = excluded.conservacion,
        volumen_minimo = excluded.volumen_minimo,
        instrucciones = excluded.instrucciones,
        tiempo_entrega_dias = excluded.tiempo_entrega_dias,
        costo_proveedor = excluded.costo_proveedor,
        actualizado_en = now();
    return new;
end;
$$;

drop trigger if exists trg_crear_seguimiento_estudio_externo on public.orden_pruebas_detalle;
create trigger trg_crear_seguimiento_estudio_externo
after insert or update of prueba_id, procesamiento, proveedor_servicio_id
on public.orden_pruebas_detalle
for each row execute function public.crear_seguimiento_estudio_externo_app();

update public.orden_pruebas_detalle d
set procesamiento = p.procesamiento,
    proveedor_servicio_id = p.proveedor_servicio_id
from public.pruebas_clinicas p
where p.id = d.prueba_id;

insert into public.estudios_externos (
    orden_detalle_id, orden_id, prueba_id, proveedor_id, tipo_muestra,
    recipiente, conservacion, volumen_minimo, instrucciones,
    tiempo_entrega_dias, costo_proveedor
)
select d.id, d.orden_id, d.prueba_id, p.proveedor_servicio_id,
       p.tipo_muestra_externa, p.recipiente_muestra, p.conservacion_muestra,
       p.volumen_minimo, p.instrucciones_envio, p.tiempo_entrega_dias,
       p.costo_proveedor
from public.orden_pruebas_detalle d
join public.pruebas_clinicas p on p.id = d.prueba_id
where p.procesamiento = 'externo'
on conflict (orden_detalle_id) do nothing;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
    'resultados_externos', 'resultados_externos', false, 8388608,
    array['application/pdf','image/jpeg','image/png','image/webp']
)
on conflict (id) do update set
    public = false,
    file_size_limit = excluded.file_size_limit,
    allowed_mime_types = excluded.allowed_mime_types;

grant select, insert, update, delete on public.estudios_externos to service_role;
grant select, insert, update, delete on public.envios_proveedor to service_role;
grant select, insert, update, delete on public.envios_proveedor_detalle to service_role;
grant usage, select on all sequences in schema public to service_role;

notify pgrst, 'reload schema';
commit;
