-- Alinea el esquema compartido con las tablas y columnas usadas por la aplicación.
-- Ejecutar desde Supabase SQL Editor.
begin;

alter table public.pruebas_clinicas add column if not exists precio numeric(10, 2);
update public.pruebas_clinicas set precio = 0.00 where precio is null;
alter table public.pruebas_clinicas
    alter column precio set default 0.00,
    alter column precio set not null;

create table if not exists public.ordenes (
    id bigint generated by default as identity primary key,
    paciente_id integer not null references public.pacientes(id),
    hospital_id integer references public.hospitales(id),
    doctor_id bigint references public.doctores(id),
    cuarto text,
    observaciones text,
    total_pruebas numeric(12, 2) not null default 0.00,
    total_abonos numeric(12, 2) not null default 0.00,
    estado text not null default 'pendiente' check (estado in ('pendiente', 'credito', 'pagada')),
    flujo text not null default 'muestra_pendiente' check (flujo in ('muestra_pendiente', 'en_quimico', 'finalizada')),
    creado_por_empleado_id integer references public.empleados(id),
    creado_en timestamp with time zone not null default now()
);

create table if not exists public.orden_pruebas_detalle (
    id bigint generated by default as identity primary key,
    orden_id bigint not null references public.ordenes(id) on delete cascade,
    prueba_id bigint references public.pruebas_clinicas(id),
    nombre_prueba text not null,
    tipo_prueba text,
    cantidad integer not null default 1 check (cantidad > 0),
    precio_unitario numeric(12, 2) not null default 0.00,
    precio_total numeric(12, 2) not null default 0.00
);

create table if not exists public.orden_abonos (
    id bigint generated by default as identity primary key,
    orden_id bigint not null references public.ordenes(id) on delete cascade,
    cantidad numeric(12, 2) not null check (cantidad > 0),
    registrado_por_empleado_id integer references public.empleados(id),
    nota text,
    fecha_abono timestamp with time zone not null default now()
);

create table if not exists public.resultados_paciente (
    id bigint generated by default as identity primary key,
    orden_id bigint not null references public.ordenes(id) on delete cascade,
    paciente_id integer not null references public.pacientes(id),
    resultado jsonb not null default '[]'::jsonb,
    estado text not null default 'en_proceso' check (estado in ('en_proceso', 'finalizado')),
    semaforo boolean not null default false,
    creado_en timestamp with time zone not null default now(),
    actualizado_en timestamp with time zone not null default now(),
    unique (orden_id, paciente_id)
);

-- No se agregan restricciones UNIQUE automáticamente: podrían fallar si ya
-- existen duplicados. Primero se incluyen índices seguros para las consultas.
create index if not exists idx_pruebas_reactivos_par on public.pruebas_reactivos(prueba_id, reactivo_id);
create index if not exists idx_valores_normales_prueba_nombre on public.valores_normales(prueba_id, lower(nombre));
create index if not exists idx_doctores_hospital_id on public.doctores(hospital_id);
create index if not exists idx_empleado_roles_empleado_id on public.empleado_roles(empleado_id);
create index if not exists idx_empleado_roles_rol_id on public.empleado_roles(rol_id);
create index if not exists idx_reactivos_proveedor_id on public.reactivos(proveedor_id);
create index if not exists idx_pruebas_reactivos_prueba_id on public.pruebas_reactivos(prueba_id);
create index if not exists idx_pruebas_reactivos_reactivo_id on public.pruebas_reactivos(reactivo_id);
create index if not exists idx_valores_normales_prueba_id on public.valores_normales(prueba_id);
create index if not exists idx_ordenes_creado_en on public.ordenes(creado_en desc);
create index if not exists idx_ordenes_flujo on public.ordenes(flujo);
create index if not exists idx_ordenes_paciente_id on public.ordenes(paciente_id);
create index if not exists idx_orden_detalle_orden_id on public.orden_pruebas_detalle(orden_id);
create index if not exists idx_orden_abonos_orden_id on public.orden_abonos(orden_id);
create index if not exists idx_resultados_orden_id on public.resultados_paciente(orden_id);

comment on column public.pruebas_clinicas.precio is 'Precio unitario usado en órdenes y reportes.';
commit;
